### ISSUE TITLE
Can't install on Magento 2.3 (PHP7.2)

### ISSUE THREAD

**Issue by bobemoe** [Mestrona/Mestrona_CategoryRedirect#12]
Can't install this on Magento 2.3 which requires PHP7.2. Package specifies only up to PHP7.1

**Comment by bobemoe** [comment]
I see PR #11 addresses this, its very old but not merged, is this abandoned?

**Comment by amenk** [comment]
@bobemoe Somehow I did not get GitHub Notifications, what a pitty

**Comment by bobemoe** [comment]
@amenk I ended up coding a TopMenu by hand so no longer need this. However that means admins can't edit the links without devs involved, so we may revisit this in the future.
