### ISSUE TITLE
Open target link

### ISSUE THREAD

**Issue by mehdichaouch** [Mestrona/Mestrona_CategoryRedirect#20]
Do you think is possible to add a target selector below the redirect input, to set for exemple `_blank`?

**Comment by amenk** [comment]
I think this would required to replace the full block class and overwrite this big method https://github.com/magento/magento2/blob/9798804c45894ac6066d0d7a823353dfee3950bb/app/code/Magento/Theme/Block/Html/Topmenu.php#L249 which would not be very upgrade safe

**Comment by mehdichaouch** [comment]
I understand and I'm agree with you.

I close this issue.
