### ISSUE TITLE
Redirect URL not works with magento 2.1.3

### ISSUE THREAD

**Issue by vadariyanikunj** [Mestrona/Mestrona_CategoryRedirect#3]
I installed this module in my Magento 2.1.3 but redirect URL not works.

**I follow below steps:**

1) Create about us cms page.

2) Add new category "About us"

3) Enter the redirect URL about-us & also tried test.html but it redirects on category URL, not a page.

After click category, it goes to category page instead of custom URL.

**I also do below thinkg:**

bin/magento setup:upgrade

bin/magento setup:static-content:deploy

bin/magento cache:flush

But not work :(

**Comment by d4nny801** [comment]
same issue.
Not working Magento ver. 2.1.3

**Comment by dswmedia** [comment]
Not working for me. Let me know if I can help to fix it

**Comment by ccomIvan** [comment]
When executing "composer require mestrona/magento-module-categoryredirect"
what Username and Password am I supposed to use? Is it the one from Magento, or my Mac . user and pass or what exactly?

**Comment by d4nny801** [comment]
your credentials are your access key in your Magento account https://marketplace.magento.com/customer/accessKeys/list/

username: public key
password: private key

**Comment by amenk** [comment]
did it work? I should work with 2.1.3 ... I am working now on 2.2.0 compat
