### ISSUE TITLE
Active state not working

### ISSUE THREAD

**Issue by Fr4nks** [Mestrona/Mestrona_CategoryRedirect#4]
Used composer to install to magento 2.1.5, active state not working.

**Comment by Fr4nks** [comment]
Looks like it's only when direct to pages without using .html, so you can't direct to home or contact. But contact.html is fine.

**Comment by Fr4nks** [comment]
Is there any way to direct to these url's like home and contact?

**Comment by amenk** [comment]
Why do you mean? That the active state is not working is a known issue.

**Comment by amenk** [comment]
Known issue, see #2
