### ISSUE TITLE
Not working on Magento 2.2

### ISSUE THREAD

**Issue by juniox** [Mestrona/Mestrona_CategoryRedirect#5]
Hello,
I have just installed Magento 2.2 and noticed this module stopped working.
The module is still enabled but the url redirect field disappeared from category page.

Another weird thing from 2.2 is that some blocks I used to remove (like newsletter stuff) are now showing on the first page... that's odd... maybe they changed something which affected this module either.

Thanks.

**Comment by Boumii** [comment]
Same to me. Updated from magento 2.1.9 to 2.2. The url redirect field disappeared from category page.

Also i seems to mess up with shop->configuration->catalog->catalog->search engine optimizatin - categoryURLsuffix which now is applied (.html) but cannot be modified

**Comment by juniox** [comment]
did you get a chance to find any workaround?
not sure if this module is till getting updates

**Comment by amenk** [comment]
@juniox I just upgraded to 2.2 and I still see the redirect field on the category page. Composer.json was updated.
So I currently can not reproduce the problem.
Did you debug this?
The other things: Did you check if it is related to that module (by disabling it)

**Comment by JanWerder** [comment]
I have the same problem. If you give me any pointers where I should look, maybe I could help you with an error message

**Comment by amenk** [comment]
@JanWerder 
Which problem exactly do you have? You are not seeing the config field? Can you send me a screenshot of your admin backend?
Did you patch the composer.json (otherwise the module can not be installed) or use the version I published today?

**Comment by XOR37H** [comment]
Just upgraded from Magento CE 2.1.9 to 2.2.0 and the extension is working fine on my install.

**Comment by neocamel** [comment]
I'm not seeing any evidence of the extension in my Magento install either, though composer confirmed that it's installed "Nothing to install or update".  I'm running Magento 2.2.3

**Comment by amenk** [comment]
Module is enabled? Caches flushed? etc... ?

**Comment by neocamel** [comment]
I tried flushing the cache, but I didn't know the module needed to be enabled. Where do I do that?

**Comment by amenk** [comment]
@neocamel php bin/magento module:enable

**Comment by neocamel** [comment]
Ahh thank you. It's working perfectly now.

Sorry about that. I'm still getting used to Magento 2. I was hoping they were going to make the 2.0 version much easier to use than 1.xxx, but apparently the Magento dev wanted to go in the other direction...

It's a great extension, but it's downright disgraceful that a system as ubiquitous as Magento still requires a third-party extension to do something as basic as DISPLAY A PAGE LINK IN THE NAV.  

But I'll save that rant for another day. Thanks for the quick support!
